### ISSUE TITLE
Any progress?

### ISSUE THREAD

**Issue by csukuangfj** [speechbrain/speechbrain.github.io#2]
Any progress?

**Comment by songtaoshi** [comment]
I am so looking forward to this project !!!!

**Comment by TParcollet** [comment]
Hey ! Good to see such enthusiasm ! 

To keep you updated, the SpeechBrain Core team has been selected, and we are now running into the administrative process ! Also, the development of the "core" of SpeechBrain has started.

**Comment by songtaoshi** [comment]
Hah, do there need undergraduate intern without publication but with strong interest : )

**Comment by TParcollet** [comment]
You can always send us an e-mail. Right now, we just finished to recruit the first wave. But we will be looking for more in 5-6 months.

**Comment by GolferChen** [comment]
Want more information about the progress of this project. How can?

**Comment by speechbrain** [comment]
We are actively working on the project. The plan is to have a first release
in June and one other at the end of the year.

Best,

Mirco

**Comment by csukuangfj** [comment]
@speechbrain 

Are there any roadmaps, plans, milestones or TODOs that can be posted here?

I guess this project will be open-sourced, is it possible that its development process
is put on GitHub?

As one law says:
> given enough eyeballs, all bugs are shallow

In addition, others interested in this project may contribute to it, for FREE.

**Comment by TParcollet** [comment]
Hey @csukuangfj you are right and we totally plan a global release that will allow everyone to contribute to the toolkit. We are internally discussing a **communication scheme**. We do not want to overstate the progress. It is important to note that the first release will be private with specific collaborators so the global release will contain everything needed for the community to build everything wanted. I would say that we should communicate during this month about the progress so far. To end with an optimistic view, most of the "core" code is done.

**Comment by TParcollet** [comment]
@csukuangfj The timeline is now available on our website ;)

**Comment by csukuangfj** [comment]
Cool!

Looking forward to the first release.

**Comment by StuartIanNaylor** [comment]
Hi can I be a kid in the back seat and ask if we are there yet? :)

I hang around a couple of opensource VoiceAI projects Mycroft, Rhasspy, Linto.
IMO the biggest frustration with VoiceAI currently is audio preprocessing and KWS as much is closed source, partial freeware and somewhere always there is some form of caveat.

In terms of audio preprocessing, echo cancellation, beam-forming, vad and MFCC with a focus of arm SoC satellites where performance/cost really needs optimised solutions.
I don't Dev anymore but I keep thinking the same frame FFT routines are run in multiple instances for the above whilst much is just a different byproduct of frame FFT to different windows results.
Its a gut feeling that much of the above is tackled as individual instances whilst combined functionality may save many ops.

One of the biggest problems with KWS has been model availability where they become closed source black boxes and available datasets and model generators are not available.
Linto are the first I have seen https://github.com/linto-ai/linto-desktoptools-hmg but strangely have adopted their own "common voice" which is great for ASR datasets but for HWS/KWS key word datasets apart from the relatively poor Google command set are still relatively rare.
I am not sure why as a web app to create a distributed database of datasets organised be Language, region, gender shouldn't be that hard or take much resource.

Custom models are far more accurate than general models for all and it would great to be able to see model switching based on MFCC diarisation of some kind and the tools so that custom models can be created.

ASR always seems to be the focus and for many are beyond dev capabilities or resources but strangely there is very liitle true opensource choices for the start of the audio stream whilst further down the line there seems to be some really good options.

So to continue in the manner I started "are we there yet?"

**Comment by StuartIanNaylor** [comment]
I noticed linagora.com and what the have done with HMG / Hotword is really great as to be able to set model & MFCC profiles with a common tool is a huge advantage.

Hopefully its the latter MFCC that will take much focus especially the underlying FFT routines that often seem to be repeated in many processes of different thread whilst the routines for a large part are just different product of those FFT routines.

VAD, EC, MFCC, Beamforming, DOA, NS all use frame based FFT but usually repetitions of extremely similar base routine of FFT.
We have solutions further down the line of audio process but in terms of opensource the initial feed is relatively sparse of effective low load audio processing.
NS can probably be dropped as it can be attained via MFCC by dropping low order energy.
Beamforming & DOA maybe processes to far for standard application processors.
VAD, EC & MFCC all share a spectral frame and sharing that load process could really help opensource otherwise commercial embedded DSP products will remain the only cost effective option for many.

**Comment by csukuangfj** [comment]
One year has passed since the opening of this issue. 

Could you please share some news about the development?

The [roadmap image](https://speechbrain.github.io/assets/com.png?style=fullsize) at <https://speechbrain.github.io/> has been revised several times. Hope that everything goes well and proceeds as planed.

**Comment by mravanelli** [comment]
Hi,
thank you for the interest in the project. The project is actually in a
very active phase and we are working hard to hopefully release a first
version in the late fall or early winter.

**Comment by michaelmcmillan** [comment]
When is the public release scheduled? Would be great with an ETA, even if it's off.

**Comment by jgbradley1** [comment]
I hate to ask because so many other people have already, but "Are we there yet?"

Any new estimates on when the first public release will happen?

**Comment by TParcollet** [comment]
Hi @jgbradley1, if the external beta testing phase ends without major updates, by the end of the month. If you want to be part of the beta testers (the beta test period will start very, very soon) feel free to send us an e-mail without your GitHub account :)

**Comment by csukuangfj** [comment]
I find that there are some links to the source code, documentation, and some colab notebook tutorials in https://github.com/speechbrain/speechbrain.github.io/tree/new_website
but there are no recipes.

Is there a separate repository for recipes?

**Comment by csukuangfj** [comment]
Closing as it has been [released][1] yesterday.

[1]: https://github.com/speechbrain/speechbrain
